# Runner of Poll

# Api version used to deploy
apiVersion: apps/v1
# Specification of the object: here deployment
kind: Deployment
# Identity of the deployment
metadata:
  name: poll
  namespace: default
# Deployment specification
spec:
  replicas: 2 # 2 pods/copy of Poll app
  selector: # Links pods
    matchLabels:
      app: poll
# Pod identification template
  template:
    metadata:
      labels:
        app: poll
# Container specification
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - k3d-cluster-tdop-agent-1
                    - k3d-cluster-tdop-agent-0
      containers: # list of containers to run (here just 1)
        - name: poll
          image: epitechcontent/t-dop-600-poll:k8s
          resources:
            limits:
              memory: "128M" # Limited memory specification
# Port exposed
          ports:
            - containerPort: 80
# Env variables
          envFrom:
            - configMapRef:
                name: poll-config
      # Define the restart policy for the pod
      restartPolicy: Always