# API Version
apiVersion: v1
# The type of the config file
kind: Secret
# Datas that describe the file
metadata:
  name: postgres-secret
  namespace: default
# Default type of a secret
type: Opaque
# The secrets
data:
  POSTGRES_USER: cG9zdGdyZXM=          # postgres in base64
  POSTGRES_PASSWORD: c2VjdXJpc2U=  # securise in base64
