# API Version
apiVersion: v1
# Type of config file
kind: Secret
# Secret identity definition
metadata:
  name: postgres-secret
  namespace: default
# Default type for secret
type: Opaque
# Secret data
data:
  POSTGRES_USER: cG9zdGdyZXM=          # postgres in base64
  POSTGRES_PASSWORD: c2VjdXJpc2U=  # securise in base64
