# Init file
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: default
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=          # postgres
  POSTGRES_PASSWORD: c2VjdXJpc2U=  # securise
